-- Create users table
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  username text NOT NULL,
  email text NOT NULL,
  role text NOT NULL CHECK (role IN ('patient', 'therapist', 'admin')),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email)
);

-- Create mood_logs table
CREATE TABLE public.mood_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date date NOT NULL DEFAULT CURRENT_DATE,
  score integer NOT NULL CHECK (score >= 1 AND score <= 5),
  emoji text NOT NULL,
  label text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mood_logs_pkey PRIMARY KEY (id)
);

-- Create appointments table
CREATE TABLE public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  therapist_name text NOT NULL,
  date date NOT NULL,
  time text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  email text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

-- Create chat_messages table
CREATE TABLE public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  sender text NOT NULL CHECK (sender IN ('user', 'aura')),
  text text NOT NULL,
  timestamp text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

-- Create categories table
CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- Create resources table
CREATE TABLE public.resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  type text NOT NULL CHECK (type IN ('article', 'video', 'exercise')),
  url_or_body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resources_pkey PRIMARY KEY (id)
);

-- Enable RLS (Row Level Security) - basic policies
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mood_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Allow all for now (for development purposes without auth enforcement yet)
CREATE POLICY "Allow all access to users" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow all access to mood_logs" ON public.mood_logs FOR ALL USING (true);
CREATE POLICY "Allow all access to appointments" ON public.appointments FOR ALL USING (true);
CREATE POLICY "Allow all access to chat_messages" ON public.chat_messages FOR ALL USING (true);
CREATE POLICY "Allow all access to categories" ON public.categories FOR ALL USING (true);
CREATE POLICY "Allow all access to resources" ON public.resources FOR ALL USING (true);

-- Create assessments table
CREATE TABLE public.assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('stress', 'anxiety', 'depression', 'burnout')),
  score integer NOT NULL,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessments_pkey PRIMARY KEY (id)
);

-- Create journal_entries table
CREATE TABLE public.journal_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text NOT NULL,
  mood_linked text,
  is_voice_generated boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id)
);

-- Create activity_logs table
CREATE TABLE public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  activity_type text NOT NULL,
  duration_minutes integer NOT NULL,
  completed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);

-- Create goals table
CREATE TABLE public.goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  target_value integer NOT NULL,
  current_value integer NOT NULL DEFAULT 0,
  status text NOT NULL CHECK (status IN ('in_progress', 'completed', 'abandoned')),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT goals_pkey PRIMARY KEY (id)
);

-- Create habits table
CREATE TABLE public.habits (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  streak integer NOT NULL DEFAULT 0,
  last_completed timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT habits_pkey PRIMARY KEY (id)
);

-- Create emergency_contacts table
CREATE TABLE public.emergency_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  relationship text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT emergency_contacts_pkey PRIMARY KEY (id)
);

-- Enable RLS for new tables
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to assessments" ON public.assessments FOR ALL USING (true);
CREATE POLICY "Allow all access to journal_entries" ON public.journal_entries FOR ALL USING (true);
CREATE POLICY "Allow all access to activity_logs" ON public.activity_logs FOR ALL USING (true);
CREATE POLICY "Allow all access to goals" ON public.goals FOR ALL USING (true);
CREATE POLICY "Allow all access to habits" ON public.habits FOR ALL USING (true);
CREATE POLICY "Allow all access to emergency_contacts" ON public.emergency_contacts FOR ALL USING (true);
-- Insert sample data
INSERT INTO public.users (id, username, email, role) VALUES 
('11111111-1111-1111-1111-111111111111', 'patient1', 'patient1@mindwell.com', 'patient'),
('22222222-2222-2222-2222-222222222222', 'sarah_jenkins', 'sarah.jenkins@mindwell.com', 'therapist'),
('33333333-3333-3333-3333-333333333333', 'admin_main', 'admin@mindwell.com', 'admin');

INSERT INTO public.mood_logs (user_id, date, score, emoji, label) VALUES
('11111111-1111-1111-1111-111111111111', '2026-06-10', 2, '😕', 'Low'),
('11111111-1111-1111-1111-111111111111', '2026-06-11', 3, '😐', 'Neutral'),
('11111111-1111-1111-1111-111111111111', '2026-06-12', 4, '🙂', 'Good');

INSERT INTO public.appointments (user_id, therapist_name, date, time, status, email) VALUES
('11111111-1111-1111-1111-111111111111', 'Dr. Sarah Jenkins', '2026-06-20', '14:00', 'pending', 'patient1@mindwell.com');

INSERT INTO public.categories (name) VALUES ('Anxiety'), ('Depression'), ('CBT Techniques'), ('Mindfulness'), ('Grief & Loss');

INSERT INTO public.resources (title, category, type, url_or_body) VALUES
('Deep Breathing 4-7-8 Exercise', 'Mindfulness', 'exercise', 'Inhale 4s, hold 7s, exhale 8s. Repeat 3×.');
